spring.application.name:
  petize
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_petize
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect